GET http://localhost:8999/posts 

###
GET http://localhost:8999/posts


###
POST http://localhost:8999/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjI3M2U4YWFhMTlhNTE4NzdjMjllZjIiLCJpYXQiOjE2NDY3Mzk2MjYsImV4cCI6MTY0NjgyNjAyNn0.hZ36p6Pps0x9b8J1WpESb7jI5EP9Lfz3m2L3xftaYMA

{
        "postText":"bmw",
        "category": "car",
        "description":"black",
        "img": "jhkhkhdcxs",
        "price": 1200.00
}

###
DELETE http://localhost:8999/posts

###
PATCH http://localhost:8999/posts
Content-Type: application/json

{
    "name":"new post"
}