GET http://localhost:8999/posts 

###
GET http://localhost:8999/posts


###
POST http://localhost:8999/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjI3M2U4YWFhMTlhNTE4NzdjMjllZjIiLCJpYXQiOjE2NDY3NDAwNzksImV4cCI6MTY0NjgyNjQ3OX0._n2T9tf230N76tF76bcZNuKPD69c61jx5C36l3UQ6vY

{
        "postText":"bmw",
        "img": "jhkhkhdcxs"
}

###
DELETE http://localhost:8999/posts

###
PATCH http://localhost:8999/posts
Content-Type: application/json

{
    "name":"new post"
}