GET https://encryptogram-backend.herokuapp.com/users

###
GET http://localhost:8999/users


###
POST http://localhost:8999/users/signup
Content-Type: application/json

{
    "email": "dallies27272@gmail.com",
    "password":"Encrypto@27",
    "phone_number":"0282726161",
    "fullname":"just a test"
        

}


###
DELETE http://localhost:8999/users/6218bc42f12ac86552779f89

###
PATCH http://localhost:8999/users/6218be31b86000072206ea8b
Content-Type: application/json

{
    "fullname":"master encrypto"
}