GET https://encryptogram-backend.herokuapp.com/users/62273e8aaa19a51877c29ef2

###
GET http://localhost:8999/users


###
POST http://localhost:8999/users/signin
Content-Type: application/json

{
        "fullname":"Diego Allies",
        "password":"Encrypto@27",
        "email": "dallies2727@gmail.com",
        "phone_number": "0684005634"

}


###
DELETE http://localhost:8999/users/6218bc42f12ac86552779f89

###
PATCH http://localhost:8999/users/6218be31b86000072206ea8b
Content-Type: application/json

{
    "fullname":"master encrypto"
}